### PR TITLE
Fix regression in #1378

### LINKED ISSUE #1365: "Open Google" blocks other actions if placed first in a routine
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.
A routine is made that contains an "Open Google", or "Open Google.com" command (this command is placed first), then other "Open" commands. (click mic icon next to the window's menu button, click the "Settings" button from the doorhanger, click "Routines" from the left side of the "Preferences" page, click "+ New routine" button, fill out the fields with the routine name and the actions that need to be done and click the "Save" button)

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the newly made routine command, e.g. "News".

### Expected result:
New tabs open corresponding to the number of routine actions that need to be made.

### Actual result:
Only the Google tab opens corresponding to the first routine action.

### Notes:
Reproduced on Mac 10.14 and Win10x64 with Firefox Nightly 76.0a1 (2020-03-23).
Not reproduced if the "Open Google"/"Open Google.com" is replaced with a "Search" or "Search Google Images" command in the routine.
Not reproduced  if the "Open Google"/"Open Google.com" is placed last in the routine. (2nd gif)
If the made routine is used multiple times, the other "Open" commands will need changing what websites to open. (see #1351)

### LINKED ISSUE #1526: Commands that need to go through "Redirect Notice" to open a page are not working properly
### Prerequisites:
Mic permissions are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up is clicked.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Say or write the "Go to Goodreads" command.

### Expected result:
Goodreads opens in a new tab.

### Actual result:
The tab doesn't go through the "Redirect Notice" to display the actual page and the doorhanger remains in the "One second..." state.

### Notes:
Reproduced on Mac 10.14 with Firefox Nightly 77.0a1 (2020-04-13).

### PR DESCRIPTION
**Pull request by dave-ok**
Before submitting a final PR, please:

- [x] Run `npm test` on your machine
- [x] Run `npm run format` to keep code formatted consistently
- [x] Reference the issue you are fixing in at least one of your commit messages, as `Fixes #X`

Fixes #1365 and Fixes #1526
@ianb Can you please review this? I also made an observation in #1365

### CODE REVIEW

**Comment by ianb** [comment]
Hmm... that `context.createTab()` and `browserUtil.createTab()` are different here is problematic, but I suspect that this will regress something else. This reverts https://github.com/mozilla/firefox-voice/commit/d01e67e9

But I'm not sure what the right resolution here is. I think there's probably something else (e.g., loadUrl) that needs to be fixed, or we have to distinguish between expected-final URLs (i.e., a destination) and expected-interstitial URLs (like an I'm Feeling Luck URL)

**Comment by ianb** [comment]
Actually I think the bug here is in `loadUrl`, at least if my guess at the problem here is correct. If you load a URL, and that URL redirects, that should be a success. We only want it to wait as long as it takes to get _away_ from the old URL. Right now we require that the URL actually resolves to the expected URL.

**Comment by dave-ok** [comment]
How about if we check if the URL is already the expected URL immediately in `loadUrl` and return right away if it is the expected URL. Then we don't have to wait anymore

**Comment by dave-ok** [comment]
@ianb I have made some changes. Can you please confirm if this is an acceptable solution?

**Comment by ianb** [comment]
While a better version of `loadUrl` would help here, really we shouldn't use `loadUrl` at all in the Google I'm Lucky searches. So I've created  #1589 that does that.

Actually fixing `loadUrl` would mean somehow deciding when to resolve. While it would be reasonable to detect the Google redirect in that function (even though it's a special case), in that case it shouldn't resolve until the redirect is forced through. Or alternately, we just detect when something has redirected and complete, perhaps by checking that the page has had at least one URL change, and that it has resolved to a status of "complete".

**Comment by dave-ok** [comment]
Thank you for explaining this thoroughly. I had a feeling my solution was too particular and a bit hacky anyways :)

**Comment by dave-ok** [comment]
@ianb I think #1589 should close #1365 as well?

**Pull request closed without merging**
