### PR TITLE
Doorhanger

### LINKED ISSUE #1321: Add examples
Add these examples so they'll appear randomly in the doorhanger.

* Find spaghetti on page
* Count my open tabs
* Open downloads

### PR DESCRIPTION
**Pull request by naima-shk**
Before submitting a final PR, please:

- [ ] Run `npm test` on your machine
- [ ] Run `npm run format` to keep code formatted consistently
- [ ] #Reference the issue you are fixing in at least one of your commit messages.
` Incomplete fix  #1321    `
 Do not merge 
 @awallin  From where does i get a list of  existing examples ?  I created intent for the purpose but could not get desired output.

### CODE REVIEW

**Comment by awallin** [comment]
@ianb can you point @naima-shk in the right direction for adding examples?

**Comment by naima-shk** [comment]
@ianb  This is the valid draft PR.

**Comment by naima-shk** [comment]
@ianb  @awallin  I tried to fix this issues in 2 ways . 
1. By creating a new intent to add more examples.
2. By replacing the existing examples.
which one is  the  right  direction?

**Comment by ianb** [comment]
@naima-shk It looks like you accidentally added a bunch of unintended files, in CherryDot and some in .vscode. It's too many files for me to actually see the ones I think you intended to submit. I'd recommend closing this PR and recreating it with only the files you intended to change.

**Pull request closed without merging**
