### PR TITLE
Fixes #1256 - config: integrate selenium in ci

### LINKED ISSUE #1256: Enable Selenium test in CI
The test added in #1254 would ideally be run in CircleCI. [This example](https://github.com/mozilla-services/screenshots/blob/master/.circleci/config.yml#L85-L100) might be helpful.

Note there's no special way to test the CI except to upload a PR, so it's likely to fix this will require uploading PRs over and over until it passes.

### PR DESCRIPTION
**Pull request by Simpcyclassy**

### CODE REVIEW

**Comment by Simpcyclassy** [comment]
@ianb please could you look at my PR?

**Comment by ianb** [comment]
I don't think this will actually run the Selenium tests or start Firefox. I'm not exactly sure what the Selenium server is, but I don't think it's necessary for what we're doing, we'll be using Firefox (via a package called geckodriver) and the test script we have should start and connect to Firefox.

**Comment by Simpcyclassy** [comment]
Alright that makes sense

**Comment by ianb** [comment]
I'm guessing this is stalled, please reopen or recreate if you want to add to it.

**Pull request closed without merging**
