### PR TITLE
config: integrate selenium in ci

### PR DESCRIPTION
**Pull request by Simpcyclassy**
Before submitting a final PR, please:

- [ ] Run `npm test` on your machine
- [ ] Run `npm run format` to keep code formatted consistently

### CODE REVIEW

**Comment by Simpcyclassy** [comment]
@ianb @awallin could you help me confirm if I am on track before I proceed optimization?

**Comment by ianb** [comment]
@Simpcyclassy Honestly you are doing some stuff I am not that familiar with, so I'm not sure. Getting this PR to pass is obviously the most important test ;)

These instructions might be helpful: https://circleci.com/docs/2.0/browser-testing/#selenium

What are you trying to do with `docker network create grid` ? Is that trying to build a Docker image?

**Comment by Simpcyclassy** [comment]
The `docker network create grid` is supposed to make it run multiple tests on multiple machines in parallel from what I understood. I was going through some documentation earlier. I will keep optimizing though until it passes then I will call your attention.

**Comment by Simpcyclassy** [comment]
@ianb I have this very weird bug where my two PRs are showing `unknown repository` as the branch, with your permission may I close this PR

**Comment by ianb** [comment]
@Simpcyclassy Yep, close and re-create PRs as much as you need

**Pull request closed without merging**
