### PR TITLE
[browser command] bookmark all tabs

### PR DESCRIPTION
**Pull request by Simpcyclassy**

### CODE REVIEW

**Comment by Simpcyclassy** [comment]
Please could you look my PR @ianb

**Comment by ianb** [comment]
I don't think this particular function makes sense. It leads to a dialog that requires the keyboard, and the functionality itself is somewhat obscure:

image

We could do this just through the bookmarks API (and then the name could be part of the utterance), but I don't think bookmarking all tabs is necessary, unless @awallin feels otherwise.

**Comment by awallin** [comment]
Yea, not sure I see a realistic scenario where someone wants to bookmark every tab they have open.

**Comment by ianb** [comment]
I think @awallin and I agree that this isn't something people will want to use.

**Pull request closed without merging**
