### PR TITLE
added note about test to README.md

### PR DESCRIPTION
**Pull request by IkkyOdufade**
Added a note about test to the README.md

Before submitting a final PR, please:

- [ ] Run `npm test` on your machine
- [ ] Run `npm run format` to keep code formatted consistently

### CODE REVIEW

**Comment by IkkyOdufade** [comment]
Ok. I’ll work on it now...

**Comment by IkkyOdufade** [comment]
Hi @ianb . I don't understand what you mean by intents? Can you explain a bit?

**Comment by ianb** [comment]
@IkkyOdufade With respect to "intents" I was thinking about phrase and example matching, but I think what you've written will be helpful now

**Comment by IkkyOdufade** [comment]
Thank you.. My first open source contribution :).

**Pull request merged**
