### PR TITLE
[browser command] Erase history

### PR DESCRIPTION
**Pull request by Simpcyclassy**
Please I need your reviews @ianb @awallin

### CODE REVIEW

**Comment by ianb** [comment]
@awallin do you have thoughts on this? It brings up this dialog:

image

**Comment by Simpcyclassy** [comment]
From the issue explanattion here https://github.com/mozilla/firefox-voice/issues/389#issuecomment-558353897 I believe it is the expected behaviour

**Comment by awallin** [comment]
Yes, that's the expected behavior. It'll be nice when we can confirm the action with "Ok" as a voice command.

**Comment by ianb** [comment]
OK. Hitting "OK" will be very hard, but eh. If we implemented our own history clearing (there are extension APIs) we could do something like "clear today's history", with our own confirmation.

**Pull request merged**
