### PR TITLE
npm run build:jsx

### PR DESCRIPTION
**Pull request by IkkyOdufade**
1. edited the package.json

### CODE REVIEW

**Comment by IkkyOdufade** [comment]
Hi @ianb . Kindly find the edits I made. Looking forward to your corrections. Thank you.

**Comment by ianb** [comment]
@IkkyOdufade Is this for #1193 ?

This will build the files into an alternate location, but it doesn't copy the results into their final destination. The files should be moved from `build/lib/...` into, for instance `extension/popup/popupController.js` (but only if the contents of the file changed). You'll probably have to write an additional script in `bin/` to move or copy the files.

**Comment by IkkyOdufade** [comment]
Hi @ianb . So I tweaked the npm run build command again to `"build:jsx": "babel --relative --out-dir build/ --ignore gh-pages '**/*.jsx'",` to see what compiles and where it compiles to, and it compiles into 10 folders in the extension directory. I'm still trying to figure out how to write the script for checking and moving the files. The files compiled include `onboarding\onboardingController.js` and `onboarding\onboardingView.js`, in different folders.
npmbuild

**Comment by ianb** [comment]
@IkkyOdufade After a quick google I came upon this: https://github.com/babel/babel/issues/8193

Apparently babel just doesn't work right :(

With a little experimentation, this _does_ work right: 

```sh
./node_modules/.bin/babel --relative  --out-dir ../build/ --only '**/*.jsx' extension/ --verbose
```

The weird `../build/` is because it's relative to the input directory `extension/`

**Comment by IkkyOdufade** [comment]
Hi @ianb  . So is it only the changed files that gets moved to the build folder? Thank you for your help, I have been struggling with this.

**Comment by ianb** [comment]
@IkkyOdufade Everything will get built by babel, but after that only changed files should be copied into their final location (alongside the `.jsx` file)

**Comment by IkkyOdufade** [comment]
Oh ok. Do I still need to write the script that checks for changes?

**Comment by IkkyOdufade** [comment]
@ianb , this code I tweaked kinda works.
`"build:jsx": "./node_modules/.bin/babel --relative  --out-dir build/ --only . --verbose '**/*.jsx' ",`
 So firstly it creates a build folder in the extension folder and the changed files are then copied into their original location in a new build folder. So like `onboarding\build\onboardingViews.js`.

**Pull request closed without merging**
