### PR TITLE
Music services fixes - Adds commands and error messages

### LINKED ISSUE #1399: "Play audio", "Pause audio" should work
"Play audio" command should play the paused music as done by “play music”.
"Pause audio" command should pause the playing music as done by “pause music”.

This can be done by adding phrase matches in `music.toml`

### PR DESCRIPTION
**Pull request by farhatcode**
Fixes #1399 
Adds matches for "Play audio", "Pause audio" commands

### CODE REVIEW

**Comment by farhatcode** [comment]
Fixes #1401 
Adds error messages for all music services.
Displays appropriate messages on unsupported services.

**Comment by farhatcode** [comment]
> @farhatcode I'm unclear on the purpose of the checks about `tab.url.startsWith(ServiceClass.baseUrl)` ?

I added these to check and add error messages for unsupported music services, can you please see this issue:
https://github.com/mozilla/firefox-voice/issues/1401
and my description here:
https://github.com/mozilla/firefox-voice/issues/1401#issuecomment-605577207

**Comment by farhatcode** [comment]
> It's currently possible, for instance, to control Spotify when it's in a background tab. This would seem to break that.

In that case, can you please guide me to the right direction, where I should add those checks and error messages for unsupported services?

**Comment by ianb** [comment]
@farhatcode Errrr... I'm a little unclear what the intention is here, but I _think_ you are trying to catch cases where the service doesn't implement something. For instance, if you want to catch cases where the service doesn't support mute, you could change it to:

```js
intentRunner.registerIntent({
  name: "music.mute",
  async run(context) {
    const service = await getService(context, { lookAtCurrentTab: true });
    if (!service.mute) {
      const exc = new Error(`${service.name} does not implement mute`);
      exc.displayMessage = `Sorry, ${service.title} does not implement mute`;
      throw exc;
    }
    await service.mute();
  },
});
```

But unfortunately because `musicService.MusicService` implements most of these methods, that test (`!service.mute`) probably won't work – instead something else will fail. It might make more sense to just do:

```js
try {
  await service.mute();
} catch (e) {
  if (e.message === "... not sure what ...") {
    e.displayMessage = `I don't know how to mute ${service.title}, sorry`;
  }
  throw e;
}
```

**Comment by farhatcode** [comment]
@ianb I wanted to add error messages for unsupported services, so when a user say play/pause, mute/umnute, increase/decrease volume or any other music player commands. They don't receive errors.

**Comment by ianb** [comment]
Per my comment, I don't believe this code change fits our goals: https://github.com/mozilla/firefox-voice/issues/1401#issuecomment-610093675

**Pull request closed without merging**
