### PR TITLE
Update config.yml- Disabling circleci for gh pages

### LINKED ISSUE #620: Disable circleci for gh-pages branch
E.g., [this attempt](https://circleci.com/gh/mozilla/firefox-voice/1057) to build gh-pages failed.

### PR DESCRIPTION
**Pull request by lelouchB**
Fixes #620 
Before submitting a final PR, please:

- [x] Run `npm test` on your machine
- [x] Run `npm run format` to keep code formatted consistently
- [x] Reference the issue you are fixing in at least one of your commit messages, as `Fixes #X`

### CODE REVIEW

**Comment by lelouchB** [comment]
@ianb  I think this should work, but there is no way of confirming for me
What do you think about the file changes??

**Comment by ianb** [comment]
I don't know, maybe? Let's give it a try. I'll make a little push to gh-pages after this.

**Comment by lelouchB** [comment]
@ianb Thnx

**Comment by ianb** [comment]
Here's what came out: https://circleci.com/gh/mozilla/firefox-voice/2819 – maybe the real problem is that gh-pages needs a config file in it (ideally a config file that does nothing, but successfully)

**Comment by lelouchB** [comment]
Yeah it might work, I will get started on it right away

**Pull request merged**
