### PR TITLE
Update lexicon.html.ejs

### PR DESCRIPTION
**Pull request by awallin**
Added pin tab example to lexicon

### CODE REVIEW

**Comment by maitrella** [comment]
@awallin For each new intent should we update lexicon file?.

**Comment by ianb** [comment]
Yeah, maybe we should add a note to the intent writing document. I thought about generating the lexicon from the code, but creating something with a reasonable structure isn't very easy.

**Comment by maitrella** [comment]
I'll keep in mind for future intents. Thanks.

**Comment by awallin** [comment]
Not every intent will need to be included in the Lexicon. We'll have to make a case by case decision. For example the "joke" intent is more of an easter egg, while the pin tab is relevant functionality and thus inculded in the Lexicon.

**Pull request merged**
