### PR TITLE
Create circleci config.yml

### LINKED ISSUE #620: Disable circleci for gh-pages branch
E.g., [this attempt](https://circleci.com/gh/mozilla/firefox-voice/1057) to build gh-pages failed.

### PR DESCRIPTION
**Pull request by lelouchB**
Fixes #620 
@ianb I think this config.yml may work
Before submitting a final PR, please:

- [x] Run `npm test` on your machine
- [x] Run `npm run format` to keep code formatted consistently
- [x] Reference the issue you are fixing in at least one of your commit messages, as `Fixes #X`

### CODE REVIEW

**Comment by lelouchB** [comment]
@ianb https://circleci.com/gh/mozilla/firefox-voice/2821
It is working maybe?
If yes then should filters branches ignore gh-pages be removed from master config file???

**Comment by ianb** [comment]
@lelouchB Yes, I think the filters could be removed from master (separate PR of course), and probably added to the gh-pages config in this PR? With a filter we might be able to tell CircleCI to not even bother the basic build step.

**Comment by lelouchB** [comment]
@ianb just a few minutes

**Comment by lelouchB** [comment]
@ianb There is no build error but I am still trying to figure out why It is still running and not ignoring the gh-pages branch

**Comment by lelouchB** [comment]
Should I keep at it or leave it?

**Comment by ianb** [comment]
@lelouchB I guess remove it since it doesn't do anything. Then I think this will be ready to land

**Pull request merged**
