### PR TITLE
[browser command] minimize and zoom window

### PR DESCRIPTION
**Pull request by Simpcyclassy**
Please check this out @ianb

### CODE REVIEW

**Comment by awallin** [comment]
This is a great feature. Thanks @Simpcyclassy. Can you add the following aliases for minimize?
* Minimize
* Hide window

**Comment by Simpcyclassy** [comment]
Thank you! Adding them right away

**Comment by Simpcyclassy** [comment]
I have them added @awallin

**Comment by Simpcyclassy** [comment]
I just resolved all my conflicting PRs @ianb

**Pull request merged**
