### PR TITLE
[browser command] view page source

### PR DESCRIPTION
**Pull request by Simpcyclassy**

### CODE REVIEW

**Comment by Simpcyclassy** [comment]
Please have a look at my PR @ianb

**Comment by awallin** [comment]
@Simpcyclassy This is a nice intent. Can you also add the following aliases?

* view source
* view html
* view html source

**Comment by Simpcyclassy** [comment]
Thank you. I did not find the commands for these but I can add that of page info if that's fine

**Comment by Simpcyclassy** [comment]
I have just added them @awallin

**Pull request merged**
