### PR TITLE
Handles exception if no search result found

### LINKED ISSUE #702: "Doorhanger" not displayed properly if a long unbroken string command is made
### Prerequisites:
Mic permission are enabled.
"Allow" or "Don't Allow" button from “Allow Firefox Voice to Collect Voice Transcriptions” pop-up needs to be clicked.
"A privacy reminder from Google" is reviewed and agreed and the yellow language pop-up is closed.

### STR:
1. Use the shortcut or click on the mic icon from the browser toolbar.
2. Write an unbroken string of 129 characters and press the "Enter" key.

### Expected result:
There are no display issues.

### Actual result:
There are display issues in how the "Doorhanger" is shown.

### Notes:
Reproduced on Mac 10.14.6 and Win10x64 with Firefox Nightly 72.0a1 (64-bit).

### PR DESCRIPTION
**Pull request by GangaChatrvedi**
Fixes #702 

Before submitting a final PR, please:

- [x] Run `npm test` on your machine
- [x] Run `npm run format` to keep code formatted consistently

### CODE REVIEW

**Comment by ianb** [comment]
@GangaChatrvedi #702 is about long strings in the doorhanger. I'm a little unclear what this is fixing? Can you give some details on what you have to do to get the bug being fixed here?

**Comment by GangaChatrvedi** [comment]
@ianb I think layout issue in #702 is because of an exception when there is no search result for query so this is fixing that issue by handling exception.

**Comment by ianb** [comment]
@GangaChatrvedi #702 only looks like a layout issue, something like `text-overflow` (or other CSS) is probably all that's needed to fix it. The search result shouldn't really matter.

It's possible you encountered a regression from #1180 which he's trying to fix in #1236 ...?

**Comment by GangaChatrvedi** [comment]
@ianb I was taking a look again at #702 and reconfirmed that it is certainly not a css issue as with 129 char string we have a complete blank screen on doorhanger. When checked it leaded to exception of no result found.

This all is happening because of search rule of google
- max 50 words
- each word of max 128 char

We have one of 2 possible solution to overcome this error.
- Trim each word by 128 char
- Show that we could not find any result. Because its came thing that google is going as well on general search page.


This will work
https://www.google.com/search?q=hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

This will not
https://www.google.com/search?q=hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by ianb** [comment]
While trying to understand this I keep getting [this fine image](https://imgur.com/t/hhhhhhhhhhhhhhhhhhhhhhhhh/oW26UT4). Thanks internet!

Anyway, I guess this is OK, or at least doesn't effect anything badly, but I haven't really been able to get to any error condition myself.

**Comment by alexandra-martin** [comment]
> I think layout issue in #702 is because of an exception when there is no search result for query

Good call @GangaChatrvedi. Indeed, with even a smaller string, that doesn't give search results on Google, the same behavior appears.

**Pull request merged**
