### PR TITLE
1542 history visual clean up

### LINKED ISSUE #1542: Visual clean up History
These are visual specific fixes (and a couple minor functional tweaks) for the display of voice history in preferences. See attached mockup.

Separate issues are being added for larger functional additions. #1543 #1544 #1545 

* Remove drop shadow around table
* Remove hover state on rows
* Update row style & size. Height 38px, alternative background color of #F2F2F2
* Change order of columns. "You said..." should be first
* Unless there's a performance issue loading 50 rows by default let's remove the option to choose number of rows and simply have pagination move through 50 at a time. There's enough real estate to rely on scrolling.
* Clear history should be a button

history

### PR DESCRIPTION
**Pull request by annlinros**
fixes #1542 

Hi @awallin 
I have made the visual clean up.
Please have a look :)

### CODE REVIEW

**Comment by awallin** [comment]
Looking better @annlinros. Noting a few discrepancies I see from the mockup. I may not have fully documented these in the issue.

* Header styling: background color: #EDEDF0, font color: #4A4A4F
* Row height should be 36px
* "You Said..." column should come before "Date"
* Reduce width of "Date" Column to about 190px (or whatever is enough to fit the new date format below)
* Date format should be MM/DD/YY, HH:MM PM/AM
* Clear history should be a button instead of the trash can icon.
* Pagination button style should be update to match mockups
* By default table should load 50 rows and there is no need for the "Rows per page" choice.

**Comment by annlinros** [comment]
@awallin  Gonna fix it all.. :)

**Comment by annlinros** [comment]
Hi @awallin 
I have made all requested changes..
I have also additionally changed 
- color of voice commands to blue
- gave a border to table
- gave right border to 'th'
- and some margin and padding fixes.

Please have a look!

**Comment by awallin** [comment]
Looking great @annlinros. Couple minor issues.

* Let's wait to add the blue color until #1544 is implemented.
* Row height should be 38px
* Row height for the header should be 30px
* Add a hover state for the "Clear Voice History" and pagination buttons. You should be able to find an example of this in the normal Firefox preference screen.

Thanks!

**Comment by annlinros** [comment]
@awallin  I have done hover state for pagination buttons already. Or did you mean for the '1-50 of 60' section ?

**Comment by annlinros** [comment]
@awallin  
I have 
- removed blue color of voice commands
-header row height is 30px
-row height is set to 38px
- added hover state for "Clear Voice History" 
Please review..

**Comment by awallin** [comment]
Looks great @annlinros!

**Comment by ianb** [comment]
Great, thank you very much @annlinros !

**Pull request merged**
